### ISSUE TITLE
启动页面按右上角的对号没有反应...

### ISSUE THREAD

**Issue by trim21** [BGmi/BGmi-Android#2]
![screenshot_20180713-194134](https://user-images.githubusercontent.com/13553903/42689918-f0e9a7ba-86d4-11e8-9927-17b525f6aedd.png)

也不知道是成功还是失败了...

**Comment by trim21** [comment]
啊 原来成功了，只是没提示…

**Comment by RicterZ** [comment]
有提示的，Toast推的，在屏幕下面。。

**Comment by trim21** [comment]
…每次按按钮输入法正好弹出来了，没注意到…
