### ISSUE TITLE
app从后台恢复后视频无法继续播放

### ISSUE THREAD

**Issue by mistzzt** [BGmi/BGmi-Android#3]
系统版本8.0.0，miui国际版8.11beta。app版本是最新release，版本1.1.1。
### 重现步骤：
- 启动app并打开视频播放
- 切回桌面
- 回到后台运行的app

此时会发生如下问题：播放器黑屏，点击播放键无反应；需要回到主页后重新播放。

不清楚是否为特定环境下才会出现；不影响正常使用。平台很不错，辛苦了。

**Comment by RicterZ** [comment]
非专业安卓开发，播放器可能不太行，回头我换个新的播放器试试，或者直接webview打开MP4文件？

**Comment by RicterZ** [comment]
https://github.com/BGmi/BGmi-Android/releases/download/1.1.2/bgmi-v1.1.2.apk
总之先用浏览器播放视频了，怎么说都比内置的这个好用（

**Comment by mistzzt** [comment]
<3
